### ISSUE TITLE
deprecated `shiny::dataTableOutput()` and hard-coded path

### ISSUE THREAD

**Issue by vincentvanhees** [habitus-eu/HabitusGUI#105]
@josefheidler just copy pasting your message here, as it is best to discuss code issues publicly when working with open source software.

> Today, I needed to process some files with Habitus, I updated everything to the newest version and I have multiple warnings and one error:
> 
> Loading required package: shiny
> Warning: package ‘shiny’ was built under R version 4.3.3
> createTcpServer: address already in use
> 
> Listening on http://127.0.0.1:4349
> `shiny::dataTableOutput()` is deprecated as of shiny 1.8.1.
> Please use `DT::DTOutput()` instead.
> Since you have a suitable version of DT (>= v0.32.1), shiny::dataTableOutput() will automatically use DT::DTOutput() under-the-hood.
> If this happens to break your app, set `options(shiny.legacy.datatable = TRUE)` to get the legacy datatable implementation (or `FALSE` to squelch this message).
> See <https://rstudio.github.io/DT/shiny.html> for more information.
> `shiny::dataTableOutput()` is deprecated as of shiny 1.8.1.
> Please use `DT::DTOutput()` instead.
> Since you have a suitable version of DT (>= v0.32.1), shiny::dataTableOutput() will automatically use DT::DTOutput() under-the-hood.
> If this happens to break your app, set `options(shiny.legacy.datatable = TRUE)` to get the legacy datatable implementation (or `FALSE` to squelch this message).
> See <https://rstudio.github.io/DT/shiny.html> for more information.
> `shiny::dataTableOutput()` is deprecated as of shiny 1.8.1.
> Please use `DT::DTOutput()` instead.
> Since you have a suitable version of DT (>= v0.32.1), shiny::dataTableOutput() will automatically use DT::DTOutput() under-the-hood.
> If this happens to break your app, set `options(shiny.legacy.datatable = TRUE)` to get the legacy datatable implementation (or `FALSE` to squelch this message).
> See <https://rstudio.github.io/DT/shiny.html> for more information.

All this is a warning about some updates on our dependencies, which seem easy to address. I just made a commit to the main branch that should address this.

> Opening fd 1
> Opening fd 2
> Error : File 'D:/Dropbox/Work/sharedfolder/DATA/Habitus/GPSprocessing/JosefMarch2024/config_GGIR_counts.csv' does not exist or is non-readable. getwd()=='C:/Users/heidl/OneDrive/Documents'
> 
> It seems that there is a hard-coded path for adding the configuration file while processing with GGIR. That path is not mine; it seems like yours. The path after getwd() is mine.

Oh, sorry, I included that path while testing and forgot to remove it by accident... I have now removed the line and made another commit.

Can you try again?

**Comment by josefheidler** [comment]
OK, thanks. That helped, but another error popped.
