### ISSUE TITLE
part3_guider' not found while processing files with GGIR

### ISSUE THREAD

**Issue by josefheidler** [habitus-eu/HabitusGUI#106]
While processing ACL counts files with Habitus/GGIR I have problem in part 3:

```
Part 3 

Busy processing ... see C:/Users/heidl/Downloads/denmark/output/output_Accelerometer/meta/ms3.out for progress
Error in { : task 3 failed - "object 'part3_guider' not found"
Calls: <Anonymous> -> g.part3 -> %myinfix% -> <Anonymous>
Execution halted
```

**Comment by vincentvanhees** [comment]
This is a GGIR specific issue (I believe for recordings without midnight or without sleep during the night). Either way, I fixed it in the weekend in a branch. I just made a PR for it https://github.com/wadpac/GGIR/pull/1112 which I will merge in the upcoming hour once all workflows have passed.

**Comment by vincentvanhees** [comment]
Just merged the branch, could you reinstall GGIR (from GitHub) and try again?

**Comment by josefheidler** [comment]
> Just merged the branch, could you reinstall GGIR (from GitHub) and try again?

Yes, it worked.

Thanks!
