### ISSUE TITLE
Missing "domains" for neighborhood in summary file (_days.csv)

### ISSUE THREAD

**Issue by josefheidler** [habitus-eu/HabitusGUI#108]
After processing files with HabitusGUI (the whole pipeline GGIR, hbGPS, and hbGIS) and obtaining results for hbGIS, I found that the **_days.csv** file is missing neighbourhood domains.

However, I can see that in the file **_whenwhatwhere.csv**, I have neighbourhood domains, so there might be a problem only when the creation of the day's file happens.

Also, could it be related to [Error and warning while building trajectories [hbGIS] #107](https://github.com/habitus-eu/HabitusGUI/issues/107)?

**Comment by vincentvanhees** [comment]
... I am investigating, it may take a couple of days before I respond.

**Comment by vincentvanhees** [comment]
I think I found the issue and addressed it in a test branch.  In the test sets I have I now get more columns than before. For example, I now see both home_sedentary and home_nbh_sedentary, while before I only had home_sedentary. So, I think this is fixed.

Could you try it out by installing hbGIS with:
`remotes::install_github("habitus-eu/HabitusGUI", ref = "issue108_nbh_missing_in_daysoutput')`

**Comment by josefheidler** [comment]
OK, we checked the file, and it is fixed!

Thanks a lot!

`remotes::install_github("habitus-eu/hbGIS", ref = "issue108_nbh_missing_in_daysoutput", force=TRUE)`

**Comment by vincentvanhees** [comment]
Thanks, I will then merge that branch and create a new hbGIS release when also the other minor issue with the config template is fixed.
