### ISSUE TITLE
Wrong format  of palmspy-params.json.

### ISSUE THREAD

**Issue by emolinaro** [habitus-eu/HabitusGUI#24]
The PALMSpy template file (`palmspy-params.json`) is downloaded from the app web interface with an incorrect format for the input parameters: Each value stored in the JSON file is reported in square brackets. The square brackets must be removed to correctly read the parameter value.

**Comment by vincentvanhees** [comment]
I have been testing the app with the test files from the palmspy repo. So, I think I will need to update the template file in HabitusGUI accordingly.

**Comment by vincentvanhees** [comment]
Now fixed in main branch (sorry forgot to tag this issue), now closing issue.
