### ISSUE TITLE
Redirect PALMSpy stdout

### ISSUE THREAD

**Issue by emolinaro** [habitus-eu/HabitusGUI#28]
Currently only `stderr` is exported to file (`TestHabitusGUI-ucloud-...`) when PALMSpy is executed.
It would be useful if also the `stdout` is available at the end of the run.

A suggestion could be to modify the [base command](https://github.com/habitus-eu/HabitusGUI/blob/33cff8b0ee79d9261292278ad88743778c1ecdbd/R/myApp.R#L533) to redirect `stderr ` and `stdout` to the same file.

**Comment by vincentvanhees** [comment]
Good idea, I will work on it this Wednesday.
