### ISSUE TITLE
Improve tsv files for GGIR

### ISSUE THREAD

**Issue by vincentvanhees** [habitus-eu/HabitusGUI#42]
I created the tsv file a while ago, it may be good to review it and where possible improve on it.

**Comment by jhmigueles** [comment]
Hi @vincentvanhees, [here a first proposal](https://github.com/habitus-eu/HabitusGUI/files/11017071/params_description_ggir.proposed.changes.xlsx) of some changes (in red) for the GGIR tsv file. Also, we could consider to include `acc.metric` and make the user able to select the SIB and SPT algorithms to be used, and then define the do.metric parameters based on that. But I'm not sure if you prefer to keep this simple and only support the default options for this in the app.

**Comment by jhmigueles** [comment]
> Yes, we can those, but the challenge with more arguments is that we also need to maintain their description text. So, ideally
> this should be kept concise. I agree on sleep arguments. My doubt about acc.metric is that we also need to include all
> do.enmo, do.mad, do.bfen, do.neishabourig, do.enmoa, etc. Although maybe you could include only these 5 ones and ignore
> the rest?

Would it be an option to handle the "do.metric" arguments internally based on the user-defined "acc.metric"?
