### ISSUE TITLE
App crashes when trying to upload config file

### ISSUE THREAD

**Issue by linematthiesen** [habitus-eu/HabitusGUI#75]
**Describe the bug**
App crashes when trying to upload a config file

**To Reproduce**
consistently reproducible via these steps
1. Open app via R studio
2. Setup as screenshot 1
3. click next
4. Setup as screenshot 2
5. click next
6. Selecting a config file (attached) and when trying to upload the app crashes and I get an error/warning in Rstudio (screenshot 3)

**Expected behavior**
To be able to upload the config file. If something is wrong with the config file I would expect to get an message with a description of the error.

**Screenshots**
Screenshot 1: 
![image](https://user-images.githubusercontent.com/130968766/232426020-03e86321-4a69-44ca-bbc6-a35197ce72fa.png)

Screenshot 2: 
![image](https://user-images.githubusercontent.com/130968766/232426075-2c678c87-b316-434b-b673-2656937a7c54.png)

Screenshot 3:
![image](https://user-images.githubusercontent.com/130968766/232426122-b80da95f-e4be-42f9-bece-66c90314db4d.png)

**Additional context**

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch from GitHub? Starting app via Rstudio: HabitusGUI::myApp(homedir=data_dir)

[config_palmsplusr.csv](https://github.com/habitus-eu/HabitusGUI/files/11247843/config_palmsplusr.csv)

**Comment by vincentvanhees** [comment]
The config file you are using is not a recent version. On screen 3 of the app you can download a new template.

The fact that the app crashed when the config file is wrong is not ideal, so I have now created a separate issue to work on that. https://github.com/habitus-eu/HabitusGUI/issues/76
