### ISSUE TITLE
Accelerometer start time error in PALMSpy input

### ISSUE THREAD

**Issue by hkucukali** [habitus-eu/HabitusGUI#81]
I am trying to run ggir+counts+palmspy pipeline over UCloud. I use raw accelerometer (.gt3x) and gps (.csv) data.
In the palmspy process, it throws the following error:
```
processing accelerometer data

Traceback (most recent call last):
  File "/home/ucloud/miniconda3/envs/palmspy/bin/palmspy", line 589, in <module>
    main(**vars(arguments))
  File "/home/ucloud/miniconda3/envs/palmspy/bin/palmspy", line 275, in main
    step, acc_data = gen_acc_dataframe(acc_data_raw, ts_name)
  File "/home/ucloud/miniconda3/envs/palmspy/lib/python3.7/site-packages/src/AccProcessing.py", line 89, in gen_acc_dataframe
    start_timestamp = datetime.strptime(start_date + " " + start_time, datetime_format[0])
  File "/home/ucloud/miniconda3/envs/palmspy/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/ucloud/miniconda3/envs/palmspy/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '23/6/2023 NA' does not match format '%m/%d/%Y %H:%M:%S'
```
I checked the counts file generated in the output/actigraph/ folder and it was like 
```
------------ Data File Created By ActiGraph wGT3XPlus ActiLife v6.10.2 Firmware v2.2.1 date format M/d/yyyy Filter Normal -----------
Serial Number: notidentified
Start Time NA
Start Date 23/6/2023
Epoch Period (hh:mm:ss) 00:00:15
Download Time NA
Download Date notidentified
Current Memory Address: 0
Current Battery Voltage: 4.03     Mode = 13
--------------------------------------------------
```
I tracked the error until the [Counts2csv.R](https://github.com/habitus-eu/HabitusGUI/blob/main/R/Counts2csv.R) file where start time is defined in below lines

```
# Create file header for the Actigraph file
start = as.POSIXlt(M$metashort$timestamp[1], format = "%Y-%m-%dT%H:%M:%S%z", desiredtz)
starttime = unlist(strsplit(as.character(start), " "))[2]
startdate = paste0(start$mday, "/", start$mon + 1, "/", start$year + 1900) #day month year 
```
I check first timestamp in the RData file in meta/basic folder and it was "2023-06-23T00:00:00+0100" and I have set desiredtz to "Europe/London" in the config file.

I run the below line in R in my computer. I saw that the time part is absent in the output (I guess because it is zero). Consequently, when it tries to split and select second value, it returns NA.

```
> as.POSIXlt("2023-06-23T00:00:00+0100", format = "%Y-%m-%dT%H:%M:%S%z", "Europe/London")
[1] "2023-06-23"
```

I think, while defining "starttime", instead of splitting this output string and getting the second value from the list, using the "strftime" function would be more smooth and solve the above mentioned error.

Therefore, I suggest a change in the line 33 of [Counts2csv.R](https://github.com/habitus-eu/HabitusGUI/blob/main/R/Counts2csv.R) as following.

```
starttime = strftime(start, format="%H:%M:%S")
```

**Comment by hkucukali** [comment]
Thanks @vincentvanhees for your response. I understand the situation with PALMSpy. I can see more improvement areas in PALMSpy but I only report issues that prevent us from using HABITUS or cause instability in itself. Otherwise, I try to change our data format on our side. I can send a pull request if it would be more convenient for you.

**Comment by vincentvanhees** [comment]
Yes, a pull request would be easier.
