### ISSUE TITLE
Default value for "interval" parameter in PALMSpy should be in integer format

### ISSUE THREAD

**Issue by hkucukali** [habitus-eu/HabitusGUI#82]
Here I suggest a very minor fix in the default parameter json for PALMSpy.

I was running HABITUS over UCLoud.
For test purposes, I used the test data in the [PALMSpy v1.9.6 release](https://github.com/emolinaro/PALMSpy/releases/tag/1.9.6):

- test_data/acc/A01_5sec.csv
- test_data/gps/A01.csv

I put the accelerometer file into a folder named "output/actigraph/" in my working directory.
I ran only the PALMSpy, using the parameter template provided in the UI and I received the following error:

```
processing accelerometer data

Traceback (most recent call last):
  File "/home/ucloud/miniconda3/envs/palmspy/bin/palmspy", line 589, in <module>
    main(**vars(arguments))
  File "/home/ucloud/miniconda3/envs/palmspy/bin/palmspy", line 281, in main
    acc_data = select_acc_intervals(acc_data, ts_name, step, interval, include_vect, include_acc).cache()
  File "/home/ucloud/miniconda3/envs/palmspy/lib/python3.7/site-packages/src/AccProcessing.py", line 547, in select_acc_intervals
    assert window >= interval, "Window smaller than epoch."
TypeError: '>=' not supported between instances of 'str' and 'int'
```

I noticed that in the default parameter json file interval value is set in str format: `"interval":"25"`.
I changed it into the int format, error resolved. 

So I suggest updating the default value for the interval to integer format: `"interval":25`

**Comment by vincentvanhees** [comment]
I am deprecating PALMSpy from HabitusGUI (see #98) and therefore will now close this issue. If you want to continue working with PALMSpy or continue to encounter issues with PALMSpy then please report them in https://github.com/emolinaro/PALMSpy.
